// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZv76vuhNfn8pes5s1AzH-t29whpeYc4',
    appId: '1:306946354086:web:bc35833beb62c8e1d5bd67',
    messagingSenderId: '306946354086',
    projectId: 'farmpure-agriplace',
    authDomain: 'farmpure-agriplace.firebaseapp.com',
    storageBucket: 'farmpure-agriplace.firebasestorage.app',
    measurementId: 'G-XMCXHMGTBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz66QK4EkA09FX2xNz9-viwXLY7WCn-Vs',
    appId: '1:306946354086:android:bfa34f5a439ff48bd5bd67',
    messagingSenderId: '306946354086',
    projectId: 'farmpure-agriplace',
    storageBucket: 'farmpure-agriplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqR42Qx1rMyphIdufqCMMTKUnmTkIbOM',
    appId: '1:306946354086:ios:8bca139780e8392ad5bd67',
    messagingSenderId: '306946354086',
    projectId: 'farmpure-agriplace',
    storageBucket: 'farmpure-agriplace.firebasestorage.app',
    iosBundleId: 'com.example.farmpure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqR42Qx1rMyphIdufqCMMTKUnmTkIbOM',
    appId: '1:306946354086:ios:8bca139780e8392ad5bd67',
    messagingSenderId: '306946354086',
    projectId: 'farmpure-agriplace',
    storageBucket: 'farmpure-agriplace.firebasestorage.app',
    iosBundleId: 'com.example.farmpure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAZv76vuhNfn8pes5s1AzH-t29whpeYc4',
    appId: '1:306946354086:web:e4cf926f085b531dd5bd67',
    messagingSenderId: '306946354086',
    projectId: 'farmpure-agriplace',
    authDomain: 'farmpure-agriplace.firebaseapp.com',
    storageBucket: 'farmpure-agriplace.firebasestorage.app',
    measurementId: 'G-C7BE3V1HVF',
  );

}